[package]
name = "actor6"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.25"
anyhow = "1.0.68"
actix = "0.13.0"
tokio = "1.23.0"
